Repository cse110-fa22-group14/cse110-fa22-group14, pull requests merged in 2022-12, with the labels that each got.

#85 Adding delete button tests
  package-lock.json
  source/__tests__/user_flow_test.js
Labels: enhancement, logic - js, testing

#91 Features/help button
  source/guidance.css
  source/guidance.html
  source/index.html
  source/scripts/guidance.js
  source/scripts/guidanceCoffeeCard.js
  source/scripts/index.js
Labels: enhancement, style - css, structure - html, logic - js, 5 - hard

#96 Upload New Tests
  source/__tests__/user_flow_test.js
Labels: testing
