Repository cse110-fa22-group14/cse110-fa22-group14, pull requests merged in 2022-11, with the labels that each got.

#41 Implemented Image Switching on Coffee Card
  source/assets/images/coffee-picture0.png
  source/assets/images/coffee-picture1.png
  source/assets/images/coffee-picture2.png
  source/assets/images/coffee-picture3.png
  source/index.css
  source/index.html
  source/scripts/switchCoffeeImage.js
Labels: enhancement, style - css, structure - html, logic - js, 3 - medium

#51 Merge Edit Button Feature into Main
  source/index.css
  source/index.html
  source/scripts/coffeeCard.js
  source/scripts/index.js
  source/scripts/switchCoffeeImage.js
Labels: enhancement, help wanted, logic - js, testing

#60 Features/deleteButton
  source/scripts/coffeeCard.js
  source/scripts/index.js
Labels: enhancement, logic - js

#68 Features/import button
  source/index.html
  source/scripts/index.js
Labels: enhancement, logic - js

#67 Features/main page design2
  source/aboutUs.html
  source/index.css
  source/index.html
  source/scripts/index.js
Labels: style - css, structure - html, logic - js

#71 Features/import upload fix
  .eslintrc.json
  .github/workflows/ci.yml
  .github/workflows/jest.yml
  README.md
  package-lock.json
  package.json
  source/__tests__/unit_tests.js
  source/__tests__/user_flow_test.js
  source/index.css
  source/index.html
  source/scripts/coffeeCard.js
  source/scripts/index.js
  source/scripts/switchCoffeeImage.js
Labels: bug, enhancement, logic - js, testing, 3 - medium

#78 Update Workflow with Automated E2E Tests
  .github/workflows/jest.yml
  package-lock.json
  package.json
  source/__tests__/user_flow_test.js
Labels: bug, testing, 5 - hard
